version: '3.8'

services:
  feeds:
    build: .
    ports:
      - "4555:4555"
    volumes:
      - ./data:/usr/src/app/data
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
